import type { Order, Product, Seller, Ticket } from './types';

export const categories = [
  'Electronics', 'Home & Kitchen', 'Fashion', 'Books', 'Beauty', 'Sports', 'Toys', 'Grocery', 'Automotive', 'Pet Supplies', 'Gift cards'
];

export const sellers: Seller[] = [
  { id: 'sel-1', name: 'Northstar Electronics', status: 'APPROVED', rating: 4.8, payoutBalance: 12450.77 },
  { id: 'sel-2', name: 'Urban Nest Goods', status: 'APPROVED', rating: 4.6, payoutBalance: 8120.30 },
  { id: 'sel-3', name: 'PageTurner Press', status: 'PENDING', rating: 4.5, payoutBalance: 2380.0 }
];

export const products: Product[] = [
  {
    id: 'p-100', slug: 'nova-noise-canceling-headphones', title: 'Nova X7 Wireless Noise-Canceling Headphones', brand: 'NovaSound', sellerId: 'sel-1', sellerName: 'Northstar Electronics', category: 'Headphones', department: 'Electronics', price: 149.99, listPrice: 219.99, rating: 4.7, reviewCount: 2438, stock: 42, badge: 'Deal of the Day', image: '/products/nova-1.jpg', images: ['/products/nova-1.jpg', '/products/nova-2.jpg'], description: 'Premium wireless headphones with adaptive noise cancellation, low-latency mode, spatial audio profile and all-day comfort.', specs: { Battery: '40 hours', Connectivity: 'Bluetooth 5.3', Weight: '245g', Warranty: '2 years' }, variants: [{ name: 'Color', values: ['Midnight', 'Pearl', 'Cobalt'] }], delivery: 'Free tomorrow delivery for AstraPlus members', fulfillment: 'AstraFulfilled', questions: [{ q: 'Does it support multipoint?', a: 'Yes, two devices simultaneously.' }], reviews: [{ user: 'Maya', rating: 5, title: 'Excellent sound', body: 'ANC and battery life are fantastic.' }]
  },
  {
    id: 'p-101', slug: 'terra-smart-air-fryer', title: 'TerraChef 8L Smart Air Fryer with Dual Zone Basket', brand: 'TerraChef', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Kitchen Appliances', department: 'Home & Kitchen', price: 119.0, listPrice: 169.0, rating: 4.5, reviewCount: 986, stock: 28, badge: 'Kitchen Favorite', image: '/products/terra-1.jpg', images: ['/products/terra-1.jpg', '/products/terra-2.jpg'], description: 'Cook crispy meals faster with synchronized dual-zone baskets, preset programs and dishwasher-safe accessories.', specs: { Capacity: '8L', Power: '1700W', Presets: '12', Material: 'BPA-free' }, variants: [{ name: 'Size', values: ['6L', '8L'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'Is the basket dishwasher safe?', a: 'Yes.' }], reviews: [{ user: 'Arjun', rating: 4, title: 'Useful daily', body: 'Great capacity for a family.' }]
  },
  {
    id: 'p-102', slug: 'orbit-4k-action-camera', title: 'OrbitCam 4K Waterproof Action Camera Bundle', brand: 'OrbitCam', sellerId: 'sel-1', sellerName: 'Northstar Electronics', category: 'Cameras', department: 'Electronics', price: 89.99, listPrice: 139.99, rating: 4.3, reviewCount: 721, stock: 67, badge: 'Bundle', image: '/products/orbit-1.jpg', images: ['/products/orbit-1.jpg', '/products/orbit-2.jpg'], description: 'Waterproof 4K action camera with stabilization, mounts, spare battery and travel case.', specs: { Resolution: '4K/60', Waterproof: '30m', Battery: '2 included', Storage: 'microSD' }, variants: [{ name: 'Bundle', values: ['Standard', 'Travel', 'Creator'] }], delivery: 'Free standard delivery', fulfillment: 'SellerFulfilled', questions: [{ q: 'Does it include a chest mount?', a: 'The Travel bundle does.' }], reviews: [{ user: 'Lena', rating: 4, title: 'Good value', body: 'Great for biking videos.' }]
  },
  {
    id: 'p-103', slug: 'aero-knit-running-shoes', title: 'AeroKnit Lightweight Running Shoes', brand: 'AeroKnit', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Shoes', department: 'Fashion', price: 64.5, listPrice: 95.0, rating: 4.4, reviewCount: 1305, stock: 95, badge: 'Top Rated', image: '/products/aero-1.jpg', images: ['/products/aero-1.jpg', '/products/aero-2.jpg'], description: 'Breathable running shoes with responsive foam, grippy outsole and everyday comfort.', specs: { Upper: 'Engineered knit', Sole: 'EVA foam', Drop: '8mm', Use: 'Road running' }, variants: [{ name: 'Size', values: ['7', '8', '9', '10', '11'] }, { name: 'Color', values: ['Black', 'Blue', 'White'] }], delivery: 'Arrives tomorrow', fulfillment: 'AstraFulfilled', questions: [{ q: 'True to size?', a: 'Most customers say yes.' }], reviews: [{ user: 'Noah', rating: 5, title: 'Comfortable', body: 'Very light for daily runs.' }]
  },
  {
    id: 'p-104', slug: 'deep-work-design-book', title: 'Designing Deep Work Systems', brand: 'PageTurner', sellerId: 'sel-3', sellerName: 'PageTurner Press', category: 'Productivity', department: 'Books', price: 18.99, listPrice: 24.99, rating: 4.8, reviewCount: 412, stock: 120, badge: 'Editor Pick', image: '/products/book-1.jpg', images: ['/products/book-1.jpg', '/products/book-2.jpg'], description: 'A practical guide to focus rituals, team cadences, automation and sustainable productivity.', specs: { Pages: '312', Format: 'Paperback', Language: 'English', ISBN: '978-0-0000-0000-1' }, variants: [{ name: 'Format', values: ['Paperback', 'Kindle-like eBook', 'Hardcover'] }], delivery: 'Instant digital option available', fulfillment: 'AstraFulfilled', questions: [{ q: 'Is there an audiobook?', a: 'Coming soon.' }], reviews: [{ user: 'Isha', rating: 5, title: 'Actionable', body: 'Useful systems without fluff.' }]
  },
  {
    id: 'p-105', slug: 'luma-skincare-starter-kit', title: 'LumaGlow Clean Skincare Starter Kit', brand: 'LumaGlow', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Skincare', department: 'Beauty', price: 39.99, listPrice: 59.99, rating: 4.2, reviewCount: 654, stock: 54, badge: 'Coupon Available', image: '/products/luma-1.jpg', images: ['/products/luma-1.jpg', '/products/luma-2.jpg'], description: 'Gentle cleanser, serum and moisturizer set with travel pouch. Fragrance-free and dermatologist tested.', specs: { Includes: '3 items', Skin: 'All skin types', Fragrance: 'Free', Cruelty: 'No animal testing' }, variants: [{ name: 'Pack', values: ['Starter', 'Full Routine'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'For sensitive skin?', a: 'Yes, patch test recommended.' }], reviews: [{ user: 'Sara', rating: 4, title: 'Gentle', body: 'Good starter kit.' }]
  },
  {
    id: 'p-106', slug: 'ridgeline-cork-yoga-mat', title: 'RidgeLine Cork Yoga Mat with Cotton Strap', brand: 'RidgeLine', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Yoga', department: 'Sports', price: 48.0, listPrice: 64.0, rating: 4.6, reviewCount: 318, stock: 73, badge: 'New', image: '/products/yoga-1.jpg', images: ['/products/yoga-1.jpg'], description: 'Natural cork face over a grippy natural-rubber base. Rolls tight, stays put in a warm studio, and the cotton strap is actually useful.', specs: { Length: '183cm', Thickness: '4mm', Face: 'Cork', Base: 'Natural rubber' }, variants: [{ name: 'Length', values: ['173cm', '183cm'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'Does cork get slippery with sweat?', a: 'It gets tackier as it warms. Wipe with a damp cloth after class.' }], reviews: [{ user: 'Priya', rating: 5, title: 'Quiet and grippy', body: 'No rubber smell. Holds a lunge without sliding.' }]
  },
  {
    id: 'p-107', slug: 'apex-pulse-adjustable-kettlebell', title: 'Apex Pulse Adjustable Kettlebell 8–24kg', brand: 'Apex Pulse', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Strength', department: 'Sports', price: 89.0, listPrice: 129.0, rating: 4.5, reviewCount: 241, stock: 40, badge: 'Space saver', image: '/products/kettle-1.jpg', images: ['/products/kettle-1.jpg'], description: 'One bell instead of a rack. Dial the load, lock the plates, and keep the handle diameter consistent from 8 to 24 kilograms.', specs: { Range: '8–24kg', Increments: '4kg', Handle: '33mm', Finish: 'Matte powder coat' }, variants: [{ name: 'Range', values: ['8–16kg', '8–24kg'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'Does it rattle?', a: 'Plates lock flush. A faint click at the start of a swing is normal.' }], reviews: [{ user: 'Dev', rating: 5, title: 'Replaced four bells', body: 'The dial is slower than bumper plates but the apartment thanks me.' }]
  },
  {
    id: 'p-108', slug: 'northwood-wooden-railway-set', title: 'Northwood Wooden Railway Starter Set', brand: 'Northwood', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Playsets', department: 'Toys', price: 54.0, listPrice: 79.0, rating: 4.7, reviewCount: 502, stock: 61, badge: 'Editor Pick', image: '/products/train-1.jpg', images: ['/products/train-1.jpg'], description: 'Beech tracks, a three-car train, a bridge and a little station. Compatible with standard wooden railways, no batteries, no app.', specs: { Pieces: '32', Wood: 'FSC beech', Age: '3+', Finish: 'Water-based paint' }, variants: [{ name: 'Set', values: ['Starter', 'Town expansion'] }], delivery: 'Arrives tomorrow', fulfillment: 'AstraFulfilled', questions: [{ q: 'Fits Brio-style tracks?', a: 'Yes. Standard wooden-railway connectors.' }], reviews: [{ user: 'Amina', rating: 5, title: 'Lasts past one afternoon', body: 'Solid joints. The bridge is the piece they actually fight over.' }]
  },
  {
    id: 'p-109', slug: 'orbit-mini-remote-buggy', title: 'Orbit Mini Remote Buggy 1:16', brand: 'OrbitCam', sellerId: 'sel-1', sellerName: 'Northstar Electronics', category: 'Remote toys', department: 'Toys', price: 36.0, listPrice: 49.0, rating: 4.3, reviewCount: 277, stock: 88, badge: 'Weekend pick', image: '/products/buggy-1.jpg', images: ['/products/buggy-1.jpg'], description: 'A compact 2.4GHz crawler with a spare tire, working roof lights and a pistol-grip remote. Built for driveways and not for water.', specs: { Scale: '1:16', Drive: '4WD', Radio: '2.4GHz', Battery: 'USB rechargeable' }, variants: [{ name: 'Color', values: ['Sand', 'Olive'] }], delivery: 'Arrives in 2 days', fulfillment: 'SellerFulfilled', questions: [{ q: 'How long is a charge?', a: 'About 25 minutes of run time. Two batteries in the box.' }], reviews: [{ user: 'Leo', rating: 4, title: 'Tough little thing', body: 'Survived a curb. Remote range is honest indoors.' }]
  },
  {
    id: 'p-110', slug: 'harbor-field-olive-oil', title: 'Harbor & Field Extra Virgin Olive Oil 750ml', brand: 'Harbor & Field', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Pantry', department: 'Grocery', price: 22.0, listPrice: 29.0, rating: 4.6, reviewCount: 190, stock: 140, badge: 'Pantry', image: '/products/olive-1.jpg', images: ['/products/olive-1.jpg'], description: 'Cold-pressed, early harvest, bottled in dark glass. Peppery finish for bread, beans and a Tuesday salad.', specs: { Volume: '750ml', Harvest: 'Early', Origin: 'Single estate', Filter: 'Unfiltered' }, variants: [{ name: 'Size', values: ['375ml', '750ml'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'Is it peppery or buttery?', a: 'Short pepper at the back of the throat. Not sweet.' }], reviews: [{ user: 'Nia', rating: 5, title: 'Actual olive oil', body: 'Tastes like olives, not like a generic yellow bottle.' }]
  },
  {
    id: 'p-111', slug: 'ember-oak-coffee', title: 'Ember & Oak Single Origin Coffee 1kg', brand: 'Ember & Oak', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Coffee', department: 'Grocery', price: 28.0, listPrice: 36.0, rating: 4.5, reviewCount: 426, stock: 95, badge: 'Roasted weekly', image: '/products/coffee-1.jpg', images: ['/products/coffee-1.jpg'], description: '100% arabica, medium roast, chocolate and caramel. Roasted in small batches and packed in a kraft valve bag with a copper clip that you will reuse.', specs: { Weight: '1kg', Roast: 'Medium', Bean: '100% arabica', Grind: 'Whole bean' }, variants: [{ name: 'Grind', values: ['Whole bean', 'Filter', 'Espresso'] }], delivery: 'Arrives tomorrow', fulfillment: 'AstraFulfilled', questions: [{ q: 'How fresh?', a: 'Roast date is on the bag. We ship within a week of roast.' }], reviews: [{ user: 'Omar', rating: 5, title: 'Daily driver', body: 'Sweet enough for a moka pot, not burnt.' }]
  },
  {
    id: 'p-112', slug: 'voltkeep-jump-starter', title: 'VoltKeep Portable Jump Starter 2000A', brand: 'VoltKeep', sellerId: 'sel-1', sellerName: 'Northstar Electronics', category: 'Emergency', department: 'Automotive', price: 79.0, listPrice: 119.0, rating: 4.4, reviewCount: 361, stock: 52, badge: 'Car kit', image: '/products/jump-1.jpg', images: ['/products/jump-1.jpg'], description: 'A compact lithium jump pack with clamps, a flashlight and USB out. Rated for petrol engines up to 8L and diesel up to 6L. Keep it in the glovebox, not the trunk in a heatwave.', specs: { Peak: '2000A', Petrol: 'Up to 8L', Diesel: 'Up to 6L', Ports: 'USB-C + USB-A' }, variants: [{ name: 'Kit', values: ['Pack only', 'Pack + case'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'Works on a dead battery at 0°C?', a: 'Yes. Warm the pack in a coat pocket for a minute if it sat overnight in frost.' }], reviews: [{ user: 'Helen', rating: 5, title: 'Started a stubborn Civic', body: 'Clamps are honest copper. Charge held for months.' }]
  },
  {
    id: 'p-113', slug: 'cabinline-floor-mats', title: 'CabinLine All-Weather Floor Mats (Front pair)', brand: 'CabinLine', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Interior', department: 'Automotive', price: 64.0, listPrice: 89.0, rating: 4.3, reviewCount: 208, stock: 70, badge: 'Mud season', image: '/products/mats-1.jpg', images: ['/products/mats-1.jpg'], description: 'Deep-channel TPE mats with a raised lip and factory-hook holes. Hose them off. They do not smell like a tire shop.', specs: { Material: 'TPE', Set: 'Front pair', Fit: 'Universal trimmed', Care: 'Hose clean' }, variants: [{ name: 'Set', values: ['Front pair', 'Full set'] }], delivery: 'Arrives in 2 days', fulfillment: 'SellerFulfilled', questions: [{ q: 'Will they fit a compact hatch?', a: 'Yes if you trim the marked tabs. Measure before you cut.' }], reviews: [{ user: 'Ravi', rating: 4, title: 'Does the job', body: 'Rain and dog hair stay in the channels. A bit stiff the first week.' }]
  },
  {
    id: 'p-114', slug: 'hearthpup-slow-feeder', title: 'HearthPup Ceramic Slow Feeder Bowl', brand: 'HearthPup', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Feeding', department: 'Pet Supplies', price: 24.0, listPrice: 34.0, rating: 4.6, reviewCount: 447, stock: 110, badge: 'For gulpers', image: '/products/bowl-1.jpg', images: ['/products/bowl-1.jpg'], description: 'A heavy stoneware bowl with raised ridges that slow a greedy eater. Dishwasher safe, no plastic aftertaste, no cartoon print.', specs: { Capacity: '500ml', Material: 'Speckled ceramic', Dishwasher: 'Yes', Base: 'Unglazed foot' }, variants: [{ name: 'Size', values: ['Small', 'Medium'] }], delivery: 'Arrives tomorrow', fulfillment: 'AstraFulfilled', questions: [{ q: 'For cats too?', a: 'The small size works for cats. Medium is for dogs that inhale dinner.' }], reviews: [{ user: 'Sofia', rating: 5, title: 'Mealtime is quieter', body: 'He still finishes, just not in four seconds.' }]
  },
  {
    id: 'p-115', slug: 'trailcat-cat-carrier', title: 'TrailCat Compact Soft Cat Carrier', brand: 'TrailCat', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Travel', department: 'Pet Supplies', price: 49.0, listPrice: 69.0, rating: 4.4, reviewCount: 163, stock: 47, badge: 'Vet trips', image: '/products/carrier-1.jpg', images: ['/products/carrier-1.jpg'], description: 'Airline-underseat size, mesh on two sides, a leather shoulder strap that does not cut your hand. Zips wide enough to load a reluctant cat.', specs: { Size: '43 × 27 × 27cm', Shell: 'Waxed canvas', Mesh: 'Two panels', Airline: 'Underseat' }, variants: [{ name: 'Color', values: ['Oatmeal', 'Charcoal'] }], delivery: 'Arrives in 2 days', fulfillment: 'AstraFulfilled', questions: [{ q: 'Cabin approved?', a: 'Fits under most short-haul seats. Confirm your carrier dimensions with the airline.' }], reviews: [{ user: 'Kenji', rating: 4, title: 'Vet-day upgrade', body: 'Sturdy zippers. She can see out without escaping.' }]
  },
  {
    id: 'p-116', slug: 'astramart-gift-card-50', title: 'AstraMart Gift Card $50', brand: 'AstraMart', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Gift cards', department: 'Gift cards', price: 50.0, listPrice: 50.0, rating: 4.9, reviewCount: 88, stock: 999, badge: 'Instant', image: '/products/gift-50.jpg', images: ['/products/gift-50.jpg'], description: 'A fifty-dollar credit on AstraMart. Delivered as a physical card in the demo, applied at checkout like store credit. No expiry in this catalog.', specs: { Value: '$50', Form: 'Physical + ledger', Expiry: 'None', Redeem: 'Checkout' }, variants: [{ name: 'Delivery', values: ['Email', 'Physical'] }], delivery: 'Instant digital option available', fulfillment: 'AstraFulfilled', questions: [{ q: 'Can I stack it with WELCOME10?', a: 'Gift cards apply after coupons, down to a zero balance.' }], reviews: [{ user: 'Tara', rating: 5, title: 'Easy present', body: 'Looked like a real card, not a PDF coupon.' }]
  },
  {
    id: 'p-117', slug: 'astramart-gift-card-150', title: 'AstraMart Gift Card $150', brand: 'AstraMart', sellerId: 'sel-2', sellerName: 'Urban Nest Goods', category: 'Gift cards', department: 'Gift cards', price: 150.0, listPrice: 150.0, rating: 4.8, reviewCount: 41, stock: 999, badge: 'Instant', image: '/products/gift-150.jpg', images: ['/products/gift-150.jpg'], description: 'A hundred-and-fifty-dollar AstraMart credit. Same ledger as the $50 card, larger paper stock, same checkout redemption.', specs: { Value: '$150', Form: 'Physical + ledger', Expiry: 'None', Redeem: 'Checkout' }, variants: [{ name: 'Delivery', values: ['Email', 'Physical'] }], delivery: 'Instant digital option available', fulfillment: 'AstraFulfilled', questions: [{ q: 'Partial spend?', a: 'Yes. Remainder stays on the account as store credit.' }], reviews: [{ user: 'Jules', rating: 5, title: 'Covered a headphones gift', body: 'Balance leftover sat on the account. No fuss.' }]
  }
];

export const coupons = [
  { code: 'WELCOME10', type: 'percent', value: 10, minSubtotal: 30, description: '10% off orders over $30' },
  { code: 'ASTRAPLUS', type: 'shipping', value: 0, minSubtotal: 0, description: 'Free shipping preview' },
  { code: 'DEAL25', type: 'fixed', value: 25, minSubtotal: 150, description: '$25 off orders over $150' }
];

export const orders: Order[] = [
  { id: 'ord-9001', customerEmail: 'customer@demo.com', items: [{ productId: 'p-100', quantity: 1 }], subtotal: 149.99, shipping: 0, tax: 12.37, discount: 15, total: 147.36, status: 'SHIPPED', createdAt: '2026-06-24T10:00:00Z', tracking: 'ASTRA784512' },
  { id: 'ord-9002', customerEmail: 'customer@demo.com', items: [{ productId: 'p-104', quantity: 2 }], subtotal: 37.98, shipping: 4.99, tax: 3.13, discount: 0, total: 46.10, status: 'DELIVERED', createdAt: '2026-06-19T12:30:00Z', tracking: 'ASTRA762200' }
];

export const tickets: Ticket[] = [
  { id: 'tic-101', subject: 'Change delivery address', status: 'OPEN', priority: 'NORMAL', orderId: 'ord-9001' },
  { id: 'tic-102', subject: 'Return request for shoes', status: 'PENDING', priority: 'HIGH' }
];

