'use client';

import { useState } from 'react';

export function ReturnWorkflow() {
  const [step, setStep] = useState(1);
  const [done, setDone] = useState(false);
  if (done) return <div className="rounded-3xl bg-white p-8 text-center shadow-card"><h2 className="text-3xl font-black text-emerald-700">Return request created</h2><p className="mt-2">RMA RMA-DEMO-{Date.now().toString().slice(-4)} generated. Refund approval queue and notifications were simulated.</p></div>;
  return <div className="rounded-3xl bg-white p-6 shadow-card"><div className="mb-6 flex gap-2">{[1,2,3,4].map(n => <span key={n} className={`grid size-9 place-items-center rounded-full font-black ${n <= step ? 'bg-brand text-white' : 'bg-slate-200'}`}>{n}</span>)}</div>{step === 1 && <section><h2 className="text-2xl font-black">Select item</h2><select className="mt-4 w-full rounded-xl border px-4 py-3"><option>Nova X7 Wireless Noise-Canceling Headphones</option><option>Designing Deep Work Systems</option></select></section>}{step === 2 && <section><h2 className="text-2xl font-black">Return reason</h2><select className="mt-4 w-full rounded-xl border px-4 py-3"><option>Item arrived late</option><option>Wrong item</option><option>Damaged item</option><option>No longer needed</option></select></section>}{step === 3 && <section><h2 className="text-2xl font-black">Method and refund</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><button className="rounded-2xl border p-4 text-left font-bold">Drop-off location</button><button className="rounded-2xl border p-4 text-left font-bold">Carrier pickup</button><button className="rounded-2xl border p-4 text-left font-bold">Original payment method</button><button className="rounded-2xl border p-4 text-left font-bold">Instant store credit</button></div></section>}{step === 4 && <section><h2 className="text-2xl font-black">Review request</h2><p className="mt-2 text-slate-600">RMA, label placeholder, refund routing and admin audit event will be generated.</p></section>}<div className="mt-6 flex justify-end gap-3"><button onClick={() => setStep(Math.max(1, step - 1))} className="rounded-full border px-5 py-2 font-bold">Back</button><button onClick={() => step === 4 ? setDone(true) : setStep(step + 1)} className="rounded-full bg-coral px-5 py-2 font-bold text-white">{step === 4 ? 'Submit return' : 'Continue'}</button></div></div>;
}
