import { DashboardCard } from '@/components/DashboardCard';
import { SellerNav } from '@/components/seller/SellerNav';
import { products, sellers } from '@/lib/demoData';
import { formatMoney } from '@/lib/commerce';

export default function SellerPage() {
  const seller = sellers[0];
  const sellerProducts = products.filter(p => p.sellerId === seller.id);
  return <div className="container-page py-10"><SellerNav /><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-bold text-brand">Seller portal demo</p><h1 className="text-4xl font-black">{seller.name}</h1><p className="mt-1 text-slate-600">seller@demo.com / Demo123!</p></div><button className="rounded-full bg-coral px-6 py-3 font-bold text-white">Create listing</button></div><div className="mt-8 grid gap-5 md:grid-cols-4"><DashboardCard title="Revenue" value="$42.8K" note="Last 30 days" /><DashboardCard title="Orders" value="612" note="47 awaiting shipment" /><DashboardCard title="Inventory alerts" value="8" note="Low stock SKUs" /><DashboardCard title="Payout balance" value={formatMoney(seller.payoutBalance)} note="Next payout Friday" /></div><section className="mt-8 rounded-3xl bg-white p-6 shadow-card"><h2 className="text-2xl font-black">Listings and inventory</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Product</th><th>SKU</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>{sellerProducts.map(p => <tr key={p.id} className="border-b"><td className="py-3 font-bold">{p.title}</td><td>{p.id}</td><td>{formatMoney(p.price)}</td><td>{p.stock}</td><td><span className="rounded-full bg-emerald-50 px-3 py-1 font-bold text-emerald-700">Live</span></td><td className="font-bold text-brand">Edit · Promote</td></tr>)}</tbody></table></div></section><section className="mt-8 grid gap-5 lg:grid-cols-3"><div className="rounded-3xl bg-white p-6 shadow-card"><h2 className="font-black">Bulk import/export</h2><p className="mt-2 text-sm text-slate-600">CSV templates for product, variant and inventory upload are documented.</p></div><div className="rounded-3xl bg-white p-6 shadow-card"><h2 className="font-black">Promotions</h2><p className="mt-2 text-sm text-slate-600">Create coupons, discounts and deal submissions for moderation.</p></div><div className="rounded-3xl bg-white p-6 shadow-card"><h2 className="font-black">Support and compliance</h2><p className="mt-2 text-sm text-slate-600">Policy warnings, moderation status and ticket escalation.</p></div></section></div>;
}
